import type { DocType, Language, QabalaFormData } from './types';
import { formatShamsiNumeric, toPersianDigits } from './hijri';

const shamsi = formatShamsiNumeric(new Date());
const shamsiLocal = toPersianDigits(shamsi);

const pashto: Record<DocType, QabalaFormData> = {
  land: {
    documentNumber: '۱۴۰۳/۱۲۵',
    date: shamsiLocal,
    amount: '۴۵۰۰۰۰۰',
    amountWords: 'څلور میلیونه او پنځه سوه زره افغانۍ',
    currency: 'افغاني',
    sellers: [{ fullName: 'عبدالستار محمدزی', fatherName: 'غلام محمد', grandfatherName: 'عبدالحکیم', tazkiraNumber: '۱۴۰۳-۲۸۵-۰۰۱' }],
    buyers: [{ fullName: 'محمد اسحاق احمدزی', fatherName: 'نور احمد', grandfatherName: 'حاجي محمد', tazkiraNumber: '۱۴۰۳-۱۱۷-۰۰۲' }],
    witnesses: [
      { fullName: 'نصرالله کریمي', fatherName: 'غلام حیدر' },
      { fullName: 'محمد طاهر احمدي', fatherName: 'عبدالرزاق' },
    ],
    declarationText: '',
    notes: 'یادې ځمکې ۵۰ مېوه‌دارې ونې او د اوبو یوه څاه لري.',
    property: {
      province: 'کابل',
      district: 'دهمزنګ',
      village: 'باغبانان',
      blockNumber: 'B-۱۴',
      lotNumber: '۲۰۵',
      area: '۶۰۰',
      areaUnit: 'مربع متر',
      areaJerib: '۰',
      areaBiswa: '۶',
      landType: 'استوګنیز',
      previousDeedNumber: '',
      boundaryNorth: 'عمومي سرک، ۸ متره پلن',
      boundarySouth: 'د حاجي کریم ځمکه — ګډ دیوال',
      boundaryEast: 'د کوڅې ویاله، ۴ متره پلنه',
      boundaryWest: 'د محمد اکبر ځمکه — دیوال',
    },
  },
  house: {
    documentNumber: '۱۴۰۳/۱۲۵',
    date: shamsiLocal,
    amount: '۴۵۰۰۰۰۰',
    amountWords: 'څلور میلیونه او پنځه سوه زره افغانۍ',
    currency: 'افغاني',
    sellers: [{ fullName: 'عبدالستار محمدزی', fatherName: 'غلام محمد', grandfatherName: 'عبدالحکیم', tazkiraNumber: '۱۴۰۳-۲۸۵-۰۰۱' }],
    buyers: [{ fullName: 'محمد اسحاق احمدزی', fatherName: 'نور احمد', grandfatherName: 'حاجي محمد', tazkiraNumber: '۱۴۰۳-۱۱۷-۰۰۲' }],
    witnesses: [
      { fullName: 'نصرالله کریمي', fatherName: 'غلام حیدر' },
      { fullName: 'محمد طاهر احمدي', fatherName: 'عبدالرزاق' },
    ],
    declarationText: '',
    notes: '',
    property: {
      province: 'کابل',
      district: 'خیرخانه',
      village: 'بلاک ۵',
      blockNumber: 'C-۷',
      lotNumber: '۸۸',
      area: '۳۵۰',
      areaUnit: 'مربع متر',
      areaJerib: '۰',
      areaBiswa: '۳',
      landType: 'استوګنیز',
      previousDeedNumber: '',
      rooms: '۶',
      floors: '۲',
      yearBuilt: '۱۳۹۵',
      boundaryNorth: 'د احمد ګل کور — ګډ دیوال',
      boundarySouth: 'فرعي سرک، ۶ متره پلن',
      boundaryEast: 'د نور محمد کور — دیوال',
      boundaryWest: 'د کلي پارک',
    },
  },
  shop: {
    documentNumber: '۱۴۰۳/۱۲۵',
    date: shamsiLocal,
    amount: '۴۵۰۰۰۰۰',
    amountWords: 'څلور میلیونه او پنځه سوه زره افغانۍ',
    currency: 'افغاني',
    sellers: [{ fullName: 'عبدالستار محمدزی', fatherName: 'غلام محمد', grandfatherName: 'عبدالحکیم', tazkiraNumber: '۱۴۰۳-۲۸۵-۰۰۱' }],
    buyers: [{ fullName: 'محمد اسحاق احمدزی', fatherName: 'نور احمد', grandfatherName: 'حاجي محمد', tazkiraNumber: '۱۴۰۳-۱۱۷-۰۰۲' }],
    witnesses: [
      { fullName: 'نصرالله کریمي', fatherName: 'غلام حیدر' },
      { fullName: 'محمد طاهر احمدي', fatherName: 'عبدالرزاق' },
    ],
    declarationText: '',
    notes: '',
    property: {
      province: 'کابل',
      district: 'ښارنو',
      village: 'سوداګریز بازار',
      marketName: 'سرګردان مارکېټ',
      shopNumber: '۴۲',
      floor: 'لاندې پوړ',
      area: '۴۸',
      areaUnit: 'مربع متر',
      areaJerib: '',
      areaBiswa: '',
      boundaryNorth: '۴۳ نمبر دوکان — ګډ دیوال',
      boundarySouth: 'د مارکېټ اصلي لاره',
      boundaryEast: '۴۱ نمبر دوکان — ګډ دیوال',
      boundaryWest: 'د مارکېټ بهرنی دیوال',
    },
  },
  vehicle: {
    documentNumber: '۱۴۰۳/۱۲۵',
    date: shamsiLocal,
    amount: '۴۵۰۰۰۰۰',
    amountWords: 'څلور میلیونه او پنځه سوه زره افغانۍ',
    currency: 'افغاني',
    sellers: [{ fullName: 'عبدالستار محمدزی', fatherName: 'غلام محمد', grandfatherName: 'عبدالحکیم', tazkiraNumber: '۱۴۰۳-۲۸۵-۰۰۱' }],
    buyers: [{ fullName: 'محمد اسحاق احمدزی', fatherName: 'نور احمد', grandfatherName: 'حاجي محمد', tazkiraNumber: '۱۴۰۳-۱۱۷-۰۰۲' }],
    witnesses: [
      { fullName: 'نصرالله کریمي', fatherName: 'غلام حیدر' },
      { fullName: 'محمد طاهر احمدي', fatherName: 'عبدالرزاق' },
    ],
    declarationText: '',
    notes: '',
    property: {
      vehicleType: 'موټر',
      make: 'Toyota',
      model: 'Corolla',
      year: '۲۰۱۸',
      color: 'سپین',
      plateNumber: 'کابل-۱۲-۳۴۵',
      chassisNumber: 'JT2BF12K0X0123456',
      engineNumber: '4AFE123456',
      trafficRegNumber: 'ټرافیک-۵۶۷۸۹',
    },
  },
  garden: {
    documentNumber: '۱۴۰۳/۱۲۵',
    date: shamsiLocal,
    amount: '۴۵۰۰۰۰۰',
    amountWords: 'څلور میلیونه او پنځه سوه زره افغانۍ',
    currency: 'افغاني',
    sellers: [{ fullName: 'عبدالستار محمدزی', fatherName: 'غلام محمد', grandfatherName: 'عبدالحکیم', tazkiraNumber: '۱۴۰۳-۲۸۵-۰۰۱' }],
    buyers: [{ fullName: 'محمد اسحاق احمدزی', fatherName: 'نور احمد', grandfatherName: 'حاجي محمد', tazkiraNumber: '۱۴۰۳-۱۱۷-۰۰۲' }],
    witnesses: [
      { fullName: 'نصرالله کریمي', fatherName: 'غلام حیدر' },
      { fullName: 'محمد طاهر احمدي', fatherName: 'عبدالرزاق' },
    ],
    declarationText: '',
    notes: 'یاد باغ ۱۵۰ مېوه‌دارې ونې لري.',
    property: {
      province: 'پروان',
      district: 'جبل‌السراج',
      village: 'د حیدر کلا',
      blockNumber: 'A-۱',
      lotNumber: '۱۲',
      area: '۴۰۰۰',
      areaUnit: 'مربع متر',
      areaJerib: '۲',
      areaBiswa: '۰',
      landType: 'زراعتي',
      previousDeedNumber: '',
      treeCount: '۱۵۰',
      waterSource: 'اصلي ویاله',
      waterShare: 'درې شپې او ورځې',
      boundaryNorth: 'د عبدالرحمان باغ — دیوال او ویاله',
      boundarySouth: 'عمومي سرک، ۶ متره پلن',
      boundaryEast: 'د حاجي اسدالله ځمکه',
      boundaryWest: 'د اوبو لګولو ویاله',
    },
  },
};

const dari: Record<DocType, QabalaFormData> = {
  land: {
    documentNumber: '۱۴۰۳/۱۲۵',
    date: shamsiLocal,
    amount: '۴۵۰۰۰۰۰',
    amountWords: 'چهار میلیون و پنجصد هزار افغانی',
    currency: 'افغانی',
    sellers: [{ fullName: 'عبدالستار محمدزی', fatherName: 'غلام محمد', grandfatherName: 'عبدالحکیم', tazkiraNumber: '۱۴۰۳-۲۸۵-۰۰۱' }],
    buyers: [{ fullName: 'محمد اسحاق احمدزی', fatherName: 'نور احمد', grandfatherName: 'حاجی محمد', tazkiraNumber: '۱۴۰۳-۱۱۷-۰۰۲' }],
    witnesses: [
      { fullName: 'نصرالله کریمی', fatherName: 'غلام حیدر' },
      { fullName: 'محمد طاهر احمدی', fatherName: 'عبدالرزاق' },
    ],
    declarationText: '',
    notes: 'زمین متذکره دارای ۵۰ اصله درخت میوه‌دار و یک حلقه چاه آب می‌باشد.',
    property: {
      province: 'کابل',
      district: 'دهمزنگ',
      village: 'باغبانان',
      blockNumber: 'B-۱۴',
      lotNumber: '۲۰۵',
      area: '۶۰۰',
      areaUnit: 'متر مربع',
      areaJerib: '۰',
      areaBiswa: '۶',
      landType: 'مسکونی',
      previousDeedNumber: '',
      boundaryNorth: 'سرک عمومی به عرض ۸ متر',
      boundarySouth: 'زمین حاجی کریم — دیوار مشترک',
      boundaryEast: 'نهر کوچه به عرض ۴ متر',
      boundaryWest: 'زمین محمد اکبر — دیوار',
    },
  },
  house: {
    documentNumber: '۱۴۰۳/۱۲۵',
    date: shamsiLocal,
    amount: '۴۵۰۰۰۰۰',
    amountWords: 'چهار میلیون و پنجصد هزار افغانی',
    currency: 'افغانی',
    sellers: [{ fullName: 'عبدالستار محمدزی', fatherName: 'غلام محمد', grandfatherName: 'عبدالحکیم', tazkiraNumber: '۱۴۰۳-۲۸۵-۰۰۱' }],
    buyers: [{ fullName: 'محمد اسحاق احمدزی', fatherName: 'نور احمد', grandfatherName: 'حاجی محمد', tazkiraNumber: '۱۴۰۳-۱۱۷-۰۰۲' }],
    witnesses: [
      { fullName: 'نصرالله کریمی', fatherName: 'غلام حیدر' },
      { fullName: 'محمد طاهر احمدی', fatherName: 'عبدالرزاق' },
    ],
    declarationText: '',
    notes: '',
    property: {
      province: 'کابل',
      district: 'خیرخانه',
      village: 'بلاک ۵',
      blockNumber: 'C-۷',
      lotNumber: '۸۸',
      area: '۳۵۰',
      areaUnit: 'متر مربع',
      areaJerib: '۰',
      areaBiswa: '۳',
      landType: 'مسکونی',
      previousDeedNumber: '',
      rooms: '۶',
      floors: '۲',
      yearBuilt: '۱۳۹۵',
      boundaryNorth: 'خانه احمد گل — دیوار مشترک',
      boundarySouth: 'سرک فرعی به عرض ۶ متر',
      boundaryEast: 'خانه نور محمد — دیوار',
      boundaryWest: 'پارک محله',
    },
  },
  shop: {
    documentNumber: '۱۴۰۳/۱۲۵',
    date: shamsiLocal,
    amount: '۴۵۰۰۰۰۰',
    amountWords: 'چهار میلیون و پنجصد هزار افغانی',
    currency: 'افغانی',
    sellers: [{ fullName: 'عبدالستار محمدزی', fatherName: 'غلام محمد', grandfatherName: 'عبدالحکیم', tazkiraNumber: '۱۴۰۳-۲۸۵-۰۰۱' }],
    buyers: [{ fullName: 'محمد اسحاق احمدزی', fatherName: 'نور احمد', grandfatherName: 'حاجی محمد', tazkiraNumber: '۱۴۰۳-۱۱۷-۰۰۲' }],
    witnesses: [
      { fullName: 'نصرالله کریمی', fatherName: 'غلام حیدر' },
      { fullName: 'محمد طاهر احمدی', fatherName: 'عبدالرزاق' },
    ],
    declarationText: '',
    notes: '',
    property: {
      province: 'کابل',
      district: 'شهرنو',
      village: 'بازار تجارتی',
      marketName: 'مارکیت سرگردان',
      shopNumber: '۴۲',
      floor: 'همکف',
      area: '۴۸',
      areaUnit: 'متر مربع',
      areaJerib: '',
      areaBiswa: '',
      boundaryNorth: 'دکان شماره ۴۳ — دیوار مشترک',
      boundarySouth: 'راهرو اصلی مارکیت',
      boundaryEast: 'دکان شماره ۴۱ — دیوار مشترک',
      boundaryWest: 'دیوار بیرونی مارکیت',
    },
  },
  vehicle: {
    documentNumber: '۱۴۰۳/۱۲۵',
    date: shamsiLocal,
    amount: '۴۵۰۰۰۰۰',
    amountWords: 'چهار میلیون و پنجصد هزار افغانی',
    currency: 'افغانی',
    sellers: [{ fullName: 'عبدالستار محمدزی', fatherName: 'غلام محمد', grandfatherName: 'عبدالحکیم', tazkiraNumber: '۱۴۰۳-۲۸۵-۰۰۱' }],
    buyers: [{ fullName: 'محمد اسحاق احمدزی', fatherName: 'نور احمد', grandfatherName: 'حاجی محمد', tazkiraNumber: '۱۴۰۳-۱۱۷-۰۰۲' }],
    witnesses: [
      { fullName: 'نصرالله کریمی', fatherName: 'غلام حیدر' },
      { fullName: 'محمد طاهر احمدی', fatherName: 'عبدالرزاق' },
    ],
    declarationText: '',
    notes: '',
    property: {
      vehicleType: 'موتر',
      make: 'Toyota',
      model: 'Corolla',
      year: '۲۰۱۸',
      color: 'سفید',
      plateNumber: 'ک-۱۲-۳۴۵',
      chassisNumber: 'JT2BF12K0X0123456',
      engineNumber: '4AFE123456',
      trafficRegNumber: 'ترافیک-۵۶۷۸۹',
    },
  },
  garden: {
    documentNumber: '۱۴۰۳/۱۲۵',
    date: shamsiLocal,
    amount: '۴۵۰۰۰۰۰',
    amountWords: 'چهار میلیون و پنجصد هزار افغانی',
    currency: 'افغانی',
    sellers: [{ fullName: 'عبدالستار محمدزی', fatherName: 'غلام محمد', grandfatherName: 'عبدالحکیم', tazkiraNumber: '۱۴۰۳-۲۸۵-۰۰۱' }],
    buyers: [{ fullName: 'محمد اسحاق احمدزی', fatherName: 'نور احمد', grandfatherName: 'حاجی محمد', tazkiraNumber: '۱۴۰۳-۱۱۷-۰۰۲' }],
    witnesses: [
      { fullName: 'نصرالله کریمی', fatherName: 'غلام حیدر' },
      { fullName: 'محمد طاهر احمدی', fatherName: 'عبدالرزاق' },
    ],
    declarationText: '',
    notes: 'این باغ دارای ۱۵۰ اصله درخت میوه‌دار می‌باشد.',
    property: {
      province: 'پروان',
      district: 'جبل‌السراج',
      village: 'قلعه حیدر',
      blockNumber: 'A-۱',
      lotNumber: '۱۲',
      area: '۴۰۰۰',
      areaUnit: 'متر مربع',
      areaJerib: '۲',
      areaBiswa: '۰',
      landType: 'زراعتی',
      previousDeedNumber: '',
      treeCount: '۱۵۰',
      waterSource: 'نهر اصلی',
      waterShare: 'سه شبانه‌روز',
      boundaryNorth: 'باغ عبدالرحمان — دیوار و نهر',
      boundarySouth: 'سرک عمومی به عرض ۶ متر',
      boundaryEast: 'زمین حاجی اسدالله',
      boundaryWest: 'نهر آبیاری',
    },
  },
};

const english: Record<DocType, QabalaFormData> = {
  land: {
    documentNumber: '1403/125',
    date: shamsi,
    amount: '4500000',
    amountWords: 'Four million five hundred thousand Afghanis',
    currency: 'Afghan Afghani (AFN)',
    sellers: [{ fullName: 'Abdul Satar Mohammadzai', fatherName: 'Ghulam Mohammad', grandfatherName: 'Abdul Hakim', tazkiraNumber: '1403-285-001' }],
    buyers: [{ fullName: 'Mohammad Ishaq Ahmadzai', fatherName: 'Noor Ahmad', grandfatherName: 'Haji Mohammad', tazkiraNumber: '1403-117-002' }],
    witnesses: [
      { fullName: 'Nasrullah Karimi', fatherName: 'Ghulam Haidar' },
      { fullName: 'Mohammad Tahir Ahmadi', fatherName: 'Abdul Razzaq' },
    ],
    declarationText: '',
    notes: 'This land has 50 fruit trees and one water well.',
    property: {
      province: 'Kabul',
      district: 'Dehmazang',
      village: 'Baghbanan',
      blockNumber: 'B-14',
      lotNumber: '205',
      area: '600',
      areaUnit: 'Square Meters',
      areaJerib: '0',
      areaBiswa: '6',
      landType: 'Residential',
      previousDeedNumber: '',
      boundaryNorth: 'Public road, 8 meters wide',
      boundarySouth: "Haji Karim's land — shared wall",
      boundaryEast: 'Alley canal, 4 meters wide',
      boundaryWest: "Mohammad Akbar's land — wall",
    },
  },
  house: {
    documentNumber: '1403/125',
    date: shamsi,
    amount: '4500000',
    amountWords: 'Four million five hundred thousand Afghanis',
    currency: 'Afghan Afghani (AFN)',
    sellers: [{ fullName: 'Abdul Satar Mohammadzai', fatherName: 'Ghulam Mohammad', grandfatherName: 'Abdul Hakim', tazkiraNumber: '1403-285-001' }],
    buyers: [{ fullName: 'Mohammad Ishaq Ahmadzai', fatherName: 'Noor Ahmad', grandfatherName: 'Haji Mohammad', tazkiraNumber: '1403-117-002' }],
    witnesses: [
      { fullName: 'Nasrullah Karimi', fatherName: 'Ghulam Haidar' },
      { fullName: 'Mohammad Tahir Ahmadi', fatherName: 'Abdul Razzaq' },
    ],
    declarationText: '',
    notes: '',
    property: {
      province: 'Kabul',
      district: 'Khairkhana',
      village: 'Block 5',
      blockNumber: 'C-7',
      lotNumber: '88',
      area: '350',
      areaUnit: 'Square Meters',
      areaJerib: '0',
      areaBiswa: '3',
      landType: 'Residential',
      previousDeedNumber: '',
      rooms: '6',
      floors: '2',
      yearBuilt: '1395',
      boundaryNorth: "Ahmad Gul's house — shared wall",
      boundarySouth: 'Side road, 6 meters wide',
      boundaryEast: "Noor Mohammad's house — wall",
      boundaryWest: 'Neighborhood park',
    },
  },
  shop: {
    documentNumber: '1403/125',
    date: shamsi,
    amount: '4500000',
    amountWords: 'Four million five hundred thousand Afghanis',
    currency: 'Afghan Afghani (AFN)',
    sellers: [{ fullName: 'Abdul Satar Mohammadzai', fatherName: 'Ghulam Mohammad', grandfatherName: 'Abdul Hakim', tazkiraNumber: '1403-285-001' }],
    buyers: [{ fullName: 'Mohammad Ishaq Ahmadzai', fatherName: 'Noor Ahmad', grandfatherName: 'Haji Mohammad', tazkiraNumber: '1403-117-002' }],
    witnesses: [
      { fullName: 'Nasrullah Karimi', fatherName: 'Ghulam Haidar' },
      { fullName: 'Mohammad Tahir Ahmadi', fatherName: 'Abdul Razzaq' },
    ],
    declarationText: '',
    notes: '',
    property: {
      province: 'Kabul',
      district: 'Shahr-e Naw',
      village: 'Trade market',
      marketName: 'Sar Gardan Market',
      shopNumber: '42',
      floor: 'Ground floor',
      area: '48',
      areaUnit: 'Square Meters',
      areaJerib: '',
      areaBiswa: '',
      boundaryNorth: 'Shop 43 — shared wall',
      boundarySouth: 'Main market corridor',
      boundaryEast: 'Shop 41 — shared wall',
      boundaryWest: 'Outer market wall',
    },
  },
  vehicle: {
    documentNumber: '1403/125',
    date: shamsi,
    amount: '4500000',
    amountWords: 'Four million five hundred thousand Afghanis',
    currency: 'Afghan Afghani (AFN)',
    sellers: [{ fullName: 'Abdul Satar Mohammadzai', fatherName: 'Ghulam Mohammad', grandfatherName: 'Abdul Hakim', tazkiraNumber: '1403-285-001' }],
    buyers: [{ fullName: 'Mohammad Ishaq Ahmadzai', fatherName: 'Noor Ahmad', grandfatherName: 'Haji Mohammad', tazkiraNumber: '1403-117-002' }],
    witnesses: [
      { fullName: 'Nasrullah Karimi', fatherName: 'Ghulam Haidar' },
      { fullName: 'Mohammad Tahir Ahmadi', fatherName: 'Abdul Razzaq' },
    ],
    declarationText: '',
    notes: '',
    property: {
      vehicleType: 'Car',
      make: 'Toyota',
      model: 'Corolla',
      year: '2018',
      color: 'White',
      plateNumber: 'KBL-12-345',
      chassisNumber: 'JT2BF12K0X0123456',
      engineNumber: '4AFE123456',
      trafficRegNumber: 'Kabul Traffic-56789',
    },
  },
  garden: {
    documentNumber: '1403/125',
    date: shamsi,
    amount: '4500000',
    amountWords: 'Four million five hundred thousand Afghanis',
    currency: 'Afghan Afghani (AFN)',
    sellers: [{ fullName: 'Abdul Satar Mohammadzai', fatherName: 'Ghulam Mohammad', grandfatherName: 'Abdul Hakim', tazkiraNumber: '1403-285-001' }],
    buyers: [{ fullName: 'Mohammad Ishaq Ahmadzai', fatherName: 'Noor Ahmad', grandfatherName: 'Haji Mohammad', tazkiraNumber: '1403-117-002' }],
    witnesses: [
      { fullName: 'Nasrullah Karimi', fatherName: 'Ghulam Haidar' },
      { fullName: 'Mohammad Tahir Ahmadi', fatherName: 'Abdul Razzaq' },
    ],
    declarationText: '',
    notes: 'This garden has 150 fruit trees.',
    property: {
      province: 'Parwan',
      district: 'Jabal Saraj',
      village: 'Qala-e-Haidar',
      blockNumber: 'A-1',
      lotNumber: '12',
      area: '4000',
      areaUnit: 'Square Meters',
      areaJerib: '2',
      areaBiswa: '0',
      landType: 'Agricultural',
      previousDeedNumber: '',
      treeCount: '150',
      waterSource: 'Main canal',
      waterShare: 'Three days and nights',
      boundaryNorth: "Abdul Rahman's garden — wall and canal",
      boundarySouth: 'Public road, 6 meters wide',
      boundaryEast: "Haji Asadullah's land",
      boundaryWest: 'Irrigation canal',
    },
  },
};

const SAMPLES: Record<Language, Record<DocType, QabalaFormData>> = { pashto, dari, english };

export function sampleFor(lang: Language, docType: DocType): QabalaFormData {
  return SAMPLES[lang][docType];
}
